name: Node.js CI/CD pipeline

on:
  push :
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: setup aws cli
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      
      - name: Terraform setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"


      - name: Provision infrastructure using terraform
        id: provision
        run: |
          cd infrastructure
          terraform init
          terraform apply -auto-approve
          echo "ec2_public_ip=$(terraform output -raw ec2_public_ip)" >> $GITHUB_OUTPUT
      
      - name: Write EC2 SSH key to file
        run: |
          echo "${{secrets.EC2_SSH_KEY}}" > ec2_key.pem
          chmod 600 ec2_key.pem

          
      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ubuntu@${{ steps.provision.outputs.ec2_public_ip }} << 'EOF'
            set -e
            sudo apt-get update -y
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
            sudo npm i -g pm2

            git clone https://github.com/${{ secrets.USER_NAME_GITHUB }}/${{secrets.REPO_NAME}}.git
            cd ${REPO_NAME}
            npm ci || npm install

            pm2 delete ${{secrets.REPO_NAME}} || true
            pm2 start index.js --name ${{secrets.REPO_NAME}} --update-env
            pm2 save

            # optional: auto-start on reboot
            pm2 startup systemd -u ubuntu --hp /home/ubuntu | tail -n 1 | sudo bash
          EOF
